### ISSUE TITLE
Razor Sword (Relics of Hyrule) does not apply sword perks

### ISSUE THREAD

**Issue by Rizzox** [Lost-Outpost/lost-legacy#100]
Never really noticed until I did notice that my weapon wasn't applying the bleed effect from the 1h sword perk "Falling Sword." The only thing I can think of what's causing this issue, is that it is a weapon that changes into a sword from a dagger, so maybe it is not tagged properly or whatever the word is.

**Comment by Rizzox** [comment]
Just tried to put the Razor Sword on a weapon rack and the game thinks it is a dagger.

**Comment by GreatPadinski** [comment]
Hmm, yeah this is a weird one. This sword is reforged from the Kokiri Sword which is a unique dagger, but this one is clearly labeled as a sword, and this is reforged into the Gilded Sword which is also clearly labeled as a sword as well. Weird. Well I'll swap it to be a proper sword since that makes more sense to me. Fixes in 1.2.1.
