### ISSUE TITLE
Unable to download data_

### ISSUE THREAD

**Issue by ThePurpleAlien** [Lost-Outpost/lost-legacy#161]
Install failed after cc curios failed to download (i own ae + had downloaded content ingame) 
cc curios is theonly one that fails.
i have
-disabled cloud
-deleted the documents files and re-ran the game
-reinstalled the game + ae content
-tried dragging curios.esl + curios.bsa into downloads folder

**Comment by GreatPadinski** [comment]
Try verify game files, don't launch the game, then run wabbajack

**Comment by sowens2000** [comment]
How to I "verify game files" I have not heard this term before

**Comment by Squatcher97** [comment]
Just wanted to say that verifying the integrity of the files and then re-running the wabbajack install got me through the curios error.

**Comment by taehoonsong** [comment]
For anyone having the same issue, verifying the game file might not work. As of writing this post, the latest version of Lost Legacy is 1.2.1c., which I presume is built based on [this version of Skyrim](https://steamdb.info/patchnotes/12865885/). You have to downgrade your Skyrim to the correct version for this modpack to work. 

These steps are for 1.2.1c., but you can do the same in the future by changing the manifest number (explained below in Further Details section)
1. Make sure you've set the game to not auto-update. Right-click Skyrim in Steam > Updates > Only update this game when I launch it
2. Open Steam Console using the following command in a web browser or in the Windows Run menu: 
  `steam://open/console`
3. Run the following commands:
  `download_depot 489830 489831 3737743381894105176`
  `download_depot 489830 489832 4341968404481569190`
  `download_depot 489830 489833 2442187225363891157`
4. Make sure all files are downloaded. Retry if error occurs. The downloads should contain 19 files, 26 files, and 1 file, respectively.
5. These are downloaded in the steamapps\content folder (default; C:\Program Files (x86)\Steam\steamapps\content)
6. Copy the contents to your Skyrim install folder (in order)

**Further Details**
For future reference, the `download_depot` command uses three numbers. 489830 is the ID for Skyrim Special Edtion. Then, 489831, 489832, 489833 are depot numbers and the last numbers are corresponding manifest numbers as shown in steamdb. 

For example, in the first command you can see that the 489831 is the depot number and the 3737743... number matches the manifest number found in [the December 5, 2023 update for Skyrim](https://steamdb.info/patchnotes/12865885/)

I was baffled as to why verifying files didn't work for me and it was because there was another update on January 8, 2024. Hope this helps anyone in the future.

**Comment by noveldragons** [comment]
Hi, I can't move the installation past curios either. Where can I find the esl and bsa files for that to try dragging them in? I did try downloading manifest numbers as described but that did not work (I may not have done it correctly but I followed the steps and pasted them into my skyrim install folder to the best of my knowledge)
