### ISSUE TITLE
Inventory to big for screen

### ISSUE THREAD

**Issue by testnumber9000** [Lost-Outpost/lost-legacy#41]
Hello,
just finished the installation. I have an Ultra widescreen monitor 13440 x 1440
I could not find the Widescreen Mod in the optionals. Duos that mean i have to play windowed? I that is possible.
Or is this a bug that can be resolved? Because except for the Inventory’s everything works fine.

Bug: Text in a popup windows is cut of in the middle of the text. And the Inventory’s UI is not completely visible

![Screenshot308](https://user-images.githubusercontent.com/99956415/186878376-4cebb34b-34c0-4095-9b7e-72bc333b9c8c.png)
![Screenshot312](https://user-images.githubusercontent.com/99956415/186878387-aae5bb3b-676b-43df-ad5c-9738a8da16f8.png)
![Screenshot315](https://user-images.githubusercontent.com/99956415/186878394-b65f2021-57dd-4928-89eb-53ee83d24180.png)
![Skyrim Special Edition 26 08 2022 11_35_54](https://user-images.githubusercontent.com/99956415/186879947-b26fd429-ccfc-47a2-a566-6a3e4f64f3dc.png)

**Comment by GreatPadinski** [comment]
Hey sorry for the delay, not sure how I missed this. I don't have official ultrawide support yet (I have no way to test since I just have a regular monitor). But here's what another user posted in discord if it helps:
`The mods I installed to fix ultrawide for LL were:
Nordic UI 32 by 9 and 21 by 9 aspect ratio patch
UIExtensions ULTRAWIDE UI FIX (32 to 9 aspect ratio)
NORDIC UI - Ultrawide Fixes and Patches (329)


I haven't needed anything else thus far. I have not been able to find a solution for the conflict of Better Third Person Selection and moreHUD where the additional information on ingredients/enchanted items collides with the item card, and the comments made by the mod author seem to indicate there is no fix for this right now other than to disable the additional item information in moreHUD.`

If that doesn't work, your best bet is to join the discord and ask in the lost-legacy-help channel: https://discord.gg/WF66mMu

**Comment by testnumber9000** [comment]
Thank you, i will try it out ASAP:)
