### ISSUE TITLE
ref handle issue still a issue

### ISSUE THREAD

**Issue by sorenvalen** [Lost-Outpost/lost-legacy#78]
my save got bircked on the current list after starting the main quest i was a the throught of the world i am not sure how to give you my save so you can cheak no changes to the mod list beside turning off the emb and turning on one of the optinal music repalcers
[Save40_19708221_0_72656E62616E65_Tamriel_002104_20230118004617_26_1.zip](https://github.com/Lost-Outpost/lost-legacy/files/10441531/Save40_19708221_0_72656E62616E65_Tamriel_002104_20230118004617_26_1.zip)
[Save40_19708221_0_72656E62616E65_Tamriel_002104_20230118004617_26_1 (2).zip](https://github.com/Lost-Outpost/lost-legacy/files/10441532/Save40_19708221_0_72656E62616E65_Tamriel_002104_20230118004617_26_1.2.zip)
this is the file affected i am only 30 hours in at most

**Comment by GreatPadinski** [comment]
You can try to find an earlier save file before the critter spawn event starts which balloons the refr count, or start a new character. Not much I can do unfortunately.

**Comment by sorenvalen** [comment]
if i knew what was the trigger cirtier it would help me figure out how far back the issue goes in my save

**Comment by GreatPadinski** [comment]
If you look at your save in resaver, check the Active Scripts section and you might see it in there. Otherwise it might be buried under the refs in a different section. The issue is very rare, and I've see it occasionally on other wabbajack discords with no resolution, but I think it's just caused by a perfectly timed save that cuts off the critter spawning script and breaks the part that tells the script to stop, so it just repeats over and over again.
